basePath: /
definitions:
  controllers.ExpenseResponse:
    properties:
      expense:
        type: string
    type: object
  controllers.IncomeResponse:
    properties:
      income:
        type: string
    type: object
  controllers.ResponseTRF:
    properties:
      amount:
        type: number
      targetUser:
        type: integer
      type:
        type: string
    type: object
  controllers.ResponseTopup:
    properties:
      amount:
        type: number
      type:
        type: string
    type: object
  controllers.TransactionHistoryResponse:
    properties:
      amount:
        description: Jumlah transaksi
        type: number
      created_at:
        description: Timestamp transaksi
        type: string
      id:
        description: ID transaksi
        type: integer
      related_user_fullname:
        description: Nama lengkap pengguna yang terkait
        type: string
      related_user_image:
        description: Gambar pengguna yang terkait
        type: string
      related_user_phone:
        description: Nomor telepon pengguna yang terkait
        type: string
      transaction_type:
        description: '''Sent'', ''Received'', ''Top-Up'''
        type: string
      user_fullname:
        description: Nama lengkap pengguna
        type: string
      user_image:
        description: Gambar pengguna
        type: string
      user_phone:
        description: Nomor telepon pengguna
        type: string
    type: object
  dto.LoginDTO:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  dto.PinDTO:
    properties:
      pin:
        type: string
    type: object
  dto.RegisterDTO:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  dto.UpdateUserRequest:
    properties:
      email:
        type: string
      fullname:
        type: string
      image:
        type: string
      phone:
        type: string
      pin:
        maxLength: 6
        minLength: 6
        type: string
      updatedAt:
        type: string
    type: object
  dto.UserSummaryDTO:
    properties:
      email:
        type: string
      fullname:
        type: string
      id:
        type: integer
      image:
        type: string
      phone:
        type: string
    type: object
  lib.PageInfo:
    properties:
      currentPage:
        type: integer
      nextPage:
        type: integer
      prevPage:
        type: integer
      totalData:
        type: integer
      totalPage:
        type: integer
    type: object
  lib.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      pageInfo:
        $ref: '#/definitions/lib.PageInfo'
      status:
        type: integer
    type: object
  models.PaymentMethod:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      isDeleted:
        type: boolean
      name:
        type: string
      tax:
        type: number
      topupTransactions:
        items:
          $ref: '#/definitions/models.TopupTransaction'
        type: array
      updatedAt:
        type: string
    type: object
  models.TopupTransaction:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      isDeleted:
        type: boolean
      payment_method_id:
        type: integer
      transactionID:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  description: This is example for server P-Pay Aplication
  title: Backend P-Pay
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Login Account
      parameters:
      - description: Input Email
        in: formData
        name: email
        required: true
        type: string
      - description: Input Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginDTO'
      tags:
      - Auth
  /auth/pin:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Authentication Pin
      parameters:
      - description: Input Pin
        in: formData
        name: pin
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.PinDTO'
      security:
      - ApiKeyAuth: []
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Registrasi Account
      parameters:
      - description: Input Email
        in: formData
        name: email
        required: true
        type: string
      - description: Input Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.RegisterDTO'
      tags:
      - Auth
  /topup:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: topup money
      parameters:
      - description: amount of money
        in: formData
        name: amount
        type: string
      - description: select payment method
        in: formData
        name: payment_method_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResponseTopup'
      security:
      - ApiKeyAuth: []
      summary: Topup
      tags:
      - Transaction
  /transaction/expense:
    get:
      description: get user expense
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ExpenseResponse'
      security:
      - ApiKeyAuth: []
      summary: get user expense
      tags:
      - Transaction
  /transaction/history:
    get:
      description: Get Transaction History
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.TransactionHistoryResponse'
      security:
      - ApiKeyAuth: []
      summary: get history transaction
      tags:
      - Transaction
  /transaction/income:
    get:
      description: get user income
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.IncomeResponse'
      security:
      - ApiKeyAuth: []
      summary: get user income
      tags:
      - Transaction
  /transaction/payment:
    get:
      description: get payment method
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaymentMethod'
      security:
      - ApiKeyAuth: []
      summary: get payment method
      tags:
      - Transaction
  /transfer/{id}:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: transfer money
      parameters:
      - description: send to
        in: path
        name: id
        type: string
      - description: amount of money
        in: formData
        name: amount
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResponseTRF'
      security:
      - ApiKeyAuth: []
      summary: Transfer
      tags:
      - Transaction
  /users:
    get:
      consumes:
      - application/json
      description: Get All Users
      parameters:
      - description: Search Users
        in: query
        name: search
        type: string
      - description: Page Users
        in: query
        name: page
        type: integer
      - description: Limit Users
        in: query
        name: limit
        type: integer
      - description: Sort Users
        in: query
        name: sort
        type: string
      - description: Order Users
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/lib.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.UserSummaryDTO'
                  type: array
                pageInfo:
                  $ref: '#/definitions/lib.PageInfo'
              type: object
      summary: Users
      tags:
      - Users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: User
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Get Profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserSummaryDTO'
      security:
      - ApiKeyAuth: []
      tags:
      - Users
    patch:
      consumes:
      - multipart/form-data
      description: Update Movies
      parameters:
      - description: Update Full Name
        in: formData
        name: fullname
        type: string
      - description: Update Email
        in: formData
        name: email
        type: string
      - description: Update Password
        in: formData
        name: password
        type: string
      - description: Update Pin
        in: formData
        name: pin
        type: string
      - description: Update Phone
        in: formData
        name: phone
        type: string
      - description: Update Image
        in: formData
        name: image
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/lib.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.UpdateUserRequest'
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
